import { notFound } from "next/navigation";
import { CommentThread } from "@/components/comment-thread";
import { ContentHeader } from "@/components/content-header";
import { JournalFooter } from "@/components/journal-footer";
import { getAnswers, getQuestion, plainText, type Answer } from "@/lib/parse";

export const revalidate = 300;

function date(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function Avatar({ name }: { name: string }) { return <span aria-hidden="true" className="grid size-10 shrink-0 place-items-center rounded-full bg-[#e7e1d8] text-sm font-semibold text-[#8c1515]">{name.charAt(0).toUpperCase()}</span>; }
function Vote({ score }: { score: number }) { return <div className="flex shrink-0 flex-col items-center gap-1 text-zinc-500"><button aria-label="Upvote" className="grid size-8 place-items-center rounded-full text-lg transition-colors hover:bg-[#f0eeea] hover:text-[#8c1515]">▲</button><strong className="text-sm text-[#252525]">{score}</strong><button aria-label="Downvote" className="grid size-8 place-items-center rounded-full text-lg transition-colors hover:bg-[#f0eeea] hover:text-[#8c1515]">▼</button></div>; }
function AnswerCard({ answer }: { answer: Answer }) { return <article className={`grid gap-5 border-b border-[#d9d4cb] py-8 sm:grid-cols-[48px_1fr] ${answer.isAccepted ? "bg-[#f5faf6] px-4 -mx-4" : ""}`}><Vote score={answer.voteScore} /><div><div className="text-[1rem] leading-8 text-zinc-700 [&_a]:text-[#8c1515] [&_a]:underline [&_code]:bg-[#f0eeea] [&_code]:px-1 [&_li]:my-1 [&_ol]:my-5 [&_ol]:list-decimal [&_ol]:pl-6 [&_p]:my-5 [&_pre]:my-6 [&_pre]:overflow-x-auto [&_pre]:bg-[#252525] [&_pre]:p-4 [&_pre]:text-sm [&_pre]:text-white [&_ul]:my-5 [&_ul]:list-disc [&_ul]:pl-6" dangerouslySetInnerHTML={{ __html: answer.content }} />{answer.isAccepted && <p className="mt-5 text-xs font-semibold uppercase tracking-[0.12em] text-[#39754b]">✓ Accepted answer</p>}<div className="mt-6 flex items-center justify-end gap-3"><Avatar name={answer.author} /><div className="text-right text-xs"><p className="text-zinc-500">answered {date(answer.createdAt)}</p><p className="mt-1 font-semibold text-[#252525]">{answer.author}</p></div></div></div></article>; }

function IrrigationFieldBrief() { return <aside className="mt-8 border-l-4 border-[#8c1515] bg-white px-5 py-6 shadow-[0_10px_25px_rgba(30,25,20,0.05)] sm:px-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#8c1515]">Evidence-informed field brief</p><h2 className="mt-1 text-2xl font-semibold tracking-[-0.035em]">Turn satellite signals into irrigation decisions</h2></div><span className="border border-[#d9d4cb] px-2 py-1 text-xs font-medium text-zinc-600">Wheat · semi-arid systems</span></div><p className="mt-4 max-w-3xl text-[0.98rem] leading-7 text-zinc-700">Use imagery to identify patterns and priorities, then confirm every irrigation decision with field observations: soil moisture, crop stage, rainfall, pump delivery, and local weather.</p><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="border-t-2 border-[#e7e1d8] pt-3"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-[#8c1515]">1 · Monitor</p><p className="mt-2 text-sm leading-6 text-zinc-700">FAO WaPOR provides remotely sensed water-productivity data at 300 m, 100 m, and selected 20 m irrigation-scheme scales. Compare field trends over time rather than acting on one pixel.</p></div><div className="border-t-2 border-[#e7e1d8] pt-3"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-[#8c1515]">2 · Schedule</p><p className="mt-2 text-sm leading-6 text-zinc-700">Build a field water balance from local ET₀, rainfall, and root-zone moisture. FAO-56 lists a depletion fraction of 0.55 for spring wheat at ET ≈ 5 mm/day; adjust it for soil, salinity, weather, and crop stage.</p></div><div className="border-t-2 border-[#e7e1d8] pt-3"><p className="text-xs font-semibold uppercase tracking-[0.1em] text-[#8c1515]">3 · Test scenarios</p><p className="mt-2 text-sm leading-6 text-zinc-700">AquaCrop can compare full, supplemental, and deficit-irrigation scenarios. In one Kabul Basin wheat study, measured water productivity was 1.4–1.5 kg/m³ ETa; treat that as a benchmark context, not a universal target.</p></div></div><p className="mt-5 text-xs leading-5 text-zinc-500">Sources: <a className="text-[#8c1515] underline underline-offset-2" href="https://www.fao.org/in-action/remote-sensing-for-water-productivity/wapor-data/" target="_blank" rel="noreferrer">FAO WaPOR</a>, <a className="text-[#8c1515] underline underline-offset-2" href="https://www.fao.org/4/X0490E/x0490e0b.htm" target="_blank" rel="noreferrer">FAO-56</a>, and <a className="text-[#8c1515] underline underline-offset-2" href="https://agris.fao.org/search/en/providers/122535/records/65df815363b8185d9cad00ea" target="_blank" rel="noreferrer">FAO AGRIS wheat study</a>. Validate thresholds with a local irrigation adviser.</p></aside>; }

export default async function QuestionPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params; const question = await getQuestion(slug, locale); if (!question) notFound(); const answers = await getAnswers(question.id, locale);
  const answerCount = answers.length || question.answerCount; const progress = Math.min(100, Math.max(12, answerCount * 25)); const progressText = locale === "ar" ? { label: "تقدم النقاش", detail: `${answerCount} إجابات تمت مشاركتها` } : locale === "fr" ? { label: "Progression de la discussion", detail: `${answerCount} réponses partagées` } : { label: "Discussion progress", detail: `${answerCount} answers shared` };
  return <main className="min-h-screen bg-[#f5f6f8] text-[#252525]"><ContentHeader locale={locale} /><article className="mx-auto max-w-5xl px-4 py-10 sm:px-8 sm:py-16"><a href={`/${locale}/questions`} className="text-sm font-semibold text-[#8c1515] underline underline-offset-4">&larr; All questions</a><div className="mt-8 border-b border-[#c9c3b9] pb-7"><div className="flex flex-wrap gap-2">{[question.category, ...question.tags].slice(0, 5).map((tag) => <span key={tag} className="bg-[#ebe7e1] px-2 py-1 text-xs font-medium text-[#8c1515]">{tag}</span>)}</div><h1 className="mt-5 text-3xl font-semibold leading-tight tracking-[-0.04em] sm:text-5xl">{question.title}</h1><p className="mt-4 text-sm text-zinc-500">Asked {date(question.publishedAt)} · {question.viewCount} views · {question.answerCount || answers.length} answers</p></div>
    <section className="grid gap-5 py-9 sm:grid-cols-[48px_1fr]"><Vote score={question.voteScore} /><div><h2 className="sr-only">Question</h2><p className="whitespace-pre-wrap text-[1.05rem] leading-8 text-zinc-700">{plainText(question.question)}</p>{slug === "sustainable-irrigation-strategies-for-wheat-in-semi-arid-regions-pwd8g" && <IrrigationFieldBrief />}<div className="mt-7 border-y border-[#ded9d1] py-4"><div className="flex items-center justify-between gap-4 text-xs"><p className="font-semibold text-[#8c1515]">{progressText.label}</p><p className="text-zinc-500">{progressText.detail}</p></div><div role="progressbar" aria-label={progressText.label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress} className="mt-3 h-1.5 overflow-hidden bg-[#e4dfd7]"><span className="block h-full bg-[#8c1515] transition-[width] duration-700" style={{ width: `${progress}%` }}/></div></div><div className="mt-6 flex items-center justify-end gap-3"><Avatar name={question.author} /><div className="text-right text-xs"><p className="text-zinc-500">asked {date(question.publishedAt)}</p><p className="mt-1 font-semibold text-[#252525]">{question.author}</p></div></div></div></section>
    <section className="border-t border-[#c9c3b9]"><div className="flex items-baseline justify-between pt-8"><h2 className="text-2xl font-semibold tracking-[-0.035em]">{answers.length || question.answerCount} Answers</h2><a href="#comments" className="text-sm font-semibold text-[#8c1515] underline underline-offset-4">Add a comment</a></div>{answers.length ? answers.map((answer) => <AnswerCard key={answer.id} answer={answer} />) : <p className="py-8 text-sm text-zinc-500">No answers have been published yet.</p>}</section>
    <div id="discussion"><CommentThread postId={question.id} entityType="question" locale={locale} /></div>
  </article><JournalFooter locale={locale} /></main>;
}
