import { notFound } from "next/navigation";
import { CommentThread } from "@/components/comment-thread";
import { ContentHeader } from "@/components/content-header";
import { JournalFooter } from "@/components/journal-footer";
import { getAnswers, getQuestion, plainText, type Answer } from "@/lib/parse";

export const revalidate = 300;

function date(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function Avatar({ name }: { name: string }) { return <span aria-hidden="true" className="grid size-10 shrink-0 place-items-center rounded-full bg-[#e7e1d8] text-sm font-semibold text-[#8c1515]">{name.charAt(0).toUpperCase()}</span>; }
function Vote({ score }: { score: number }) { return <div className="flex shrink-0 flex-col items-center gap-1 text-zinc-500"><button aria-label="Upvote" className="grid size-8 place-items-center rounded-full text-lg transition-colors hover:bg-[#f0eeea] hover:text-[#8c1515]">▲</button><strong className="text-sm text-[#252525]">{score}</strong><button aria-label="Downvote" className="grid size-8 place-items-center rounded-full text-lg transition-colors hover:bg-[#f0eeea] hover:text-[#8c1515]">▼</button></div>; }
function AnswerCard({ answer }: { answer: Answer }) { return <article className={`grid gap-5 border-b border-[#d9d4cb] py-8 sm:grid-cols-[48px_1fr] ${answer.isAccepted ? "bg-[#f5faf6] px-4 -mx-4" : ""}`}><Vote score={answer.voteScore} /><div><div className="text-[1rem] leading-8 text-zinc-700 [&_a]:text-[#8c1515] [&_a]:underline [&_code]:bg-[#f0eeea] [&_code]:px-1 [&_li]:my-1 [&_ol]:my-5 [&_ol]:list-decimal [&_ol]:pl-6 [&_p]:my-5 [&_pre]:my-6 [&_pre]:overflow-x-auto [&_pre]:bg-[#252525] [&_pre]:p-4 [&_pre]:text-sm [&_pre]:text-white [&_ul]:my-5 [&_ul]:list-disc [&_ul]:pl-6" dangerouslySetInnerHTML={{ __html: answer.content }} />{answer.isAccepted && <p className="mt-5 text-xs font-semibold uppercase tracking-[0.12em] text-[#39754b]">✓ Accepted answer</p>}<div className="mt-6 flex items-center justify-end gap-3"><Avatar name={answer.author} /><div className="text-right text-xs"><p className="text-zinc-500">answered {date(answer.createdAt)}</p><p className="mt-1 font-semibold text-[#252525]">{answer.author}</p></div></div></div></article>; }

export default async function QuestionPage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params; const question = await getQuestion(slug, locale); if (!question) notFound(); const answers = await getAnswers(question.id, locale);
  return <main className="min-h-screen bg-[#f5f6f8] text-[#252525]"><ContentHeader locale={locale} /><article className="mx-auto max-w-5xl px-4 py-10 sm:px-8 sm:py-16"><a href={`/${locale}/questions`} className="text-sm font-semibold text-[#8c1515] underline underline-offset-4">&larr; All questions</a><div className="mt-8 border-b border-[#c9c3b9] pb-7"><div className="flex flex-wrap gap-2">{[question.category, ...question.tags].slice(0, 5).map((tag) => <span key={tag} className="bg-[#ebe7e1] px-2 py-1 text-xs font-medium text-[#8c1515]">{tag}</span>)}</div><h1 className="mt-5 text-3xl font-semibold leading-tight tracking-[-0.04em] sm:text-5xl">{question.title}</h1><p className="mt-4 text-sm text-zinc-500">Asked {date(question.publishedAt)} · {question.viewCount} views · {question.answerCount || answers.length} answers</p></div>
    <section className="grid gap-5 py-9 sm:grid-cols-[48px_1fr]"><Vote score={question.voteScore} /><div><h2 className="sr-only">Question</h2><p className="whitespace-pre-wrap text-[1.05rem] leading-8 text-zinc-700">{plainText(question.question)}</p><div className="mt-6 flex items-center justify-end gap-3"><Avatar name={question.author} /><div className="text-right text-xs"><p className="text-zinc-500">asked {date(question.publishedAt)}</p><p className="mt-1 font-semibold text-[#252525]">{question.author}</p></div></div></div></section>
    <section className="border-t border-[#c9c3b9]"><div className="flex items-baseline justify-between pt-8"><h2 className="text-2xl font-semibold tracking-[-0.035em]">{answers.length || question.answerCount} Answers</h2><a href="#discussion" className="text-sm font-semibold text-[#8c1515] underline underline-offset-4">Add an answer</a></div>{answers.length ? answers.map((answer) => <AnswerCard key={answer.id} answer={answer} />) : <p className="py-8 text-sm text-zinc-500">No answers have been published yet.</p>}</section>
    <div id="discussion"><CommentThread postId={question.id} entityType="question" locale={locale} /></div>
  </article><JournalFooter locale={locale} /></main>;
}
