import Image from "next/image";
import { ContentHeader } from "@/components/content-header";
import { JournalFooter } from "@/components/journal-footer";

const copy = {
  en: {
    eyebrow: "Web development services", title: "A website that makes your business feel established.", intro: "We design and build fast, responsive websites that turn your story into a clear next step for your customers.", cta: "Start your project", promise: "Clear scope. Modern build. Launch-ready.", processTitle: "Built around what your business needs.", process: ["A focused discovery call", "Design for every screen", "A fast, accessible build", "Launch support and handover"], packagesTitle: "Choose the right starting point", packagesNote: "Every package includes responsive design, a contact form and basic on-page SEO.", contact: "Request this package", included: "What’s included", featured: "Most complete", imageOneAlt: "People collaborating around a table", imageTwoAlt: "A speaker presenting to an audience", packages: [
      { name: "Starter site", price: "30,000 DA", description: "A polished online home for a new business or personal brand.", features: ["One custom landing page", "Mobile-first responsive design", "Contact form and map", "Basic SEO setup", "One revision round"] },
      { name: "Business site", price: "37,500 DA", description: "More room to tell your story, build trust and explain your offer.", features: ["Up to 5 custom pages", "Services and about sections", "Portfolio or gallery section", "Analytics setup", "Two revision rounds"] },
      { name: "Growth site", price: "45,000 DA", description: "A feature-rich site designed to give your growing business more momentum.", features: ["Up to 8 custom pages", "Blog or news area", "Project showcase and filters", "Newsletter signup integration", "Performance and SEO review", "Three revision rounds"] },
    ],
  },
  fr: {
    eyebrow: "Services de développement web", title: "Un site web qui donne de l’envergure à votre entreprise.", intro: "Nous concevons des sites rapides et adaptatifs qui transforment votre histoire en prochaine étape claire pour vos clients.", cta: "Démarrer votre projet", promise: "Périmètre clair. Design moderne. Prêt à lancer.", processTitle: "Conçu selon les besoins de votre entreprise.", process: ["Un appel de découverte ciblé", "Un design pour chaque écran", "Un site rapide et accessible", "Aide au lancement et prise en main"], packagesTitle: "Choisissez le bon point de départ", packagesNote: "Chaque forfait comprend un design adaptatif, un formulaire de contact et le SEO de base.", contact: "Demander ce forfait", included: "Inclus", featured: "Le plus complet", imageOneAlt: "Des personnes qui collaborent autour d’une table", imageTwoAlt: "Une personne présentant devant un public", packages: [
      { name: "Site essentiel", price: "30 000 DA", description: "Une présence en ligne soignée pour une nouvelle entreprise ou une marque personnelle.", features: ["Une page d’accueil sur mesure", "Design mobile adaptatif", "Formulaire de contact et carte", "Configuration SEO de base", "Une série de retouches"] },
      { name: "Site entreprise", price: "37 500 DA", description: "Plus d’espace pour raconter votre histoire, inspirer confiance et présenter votre offre.", features: ["Jusqu’à 5 pages sur mesure", "Pages services et à propos", "Portfolio ou galerie", "Configuration des analyses", "Deux séries de retouches"] },
      { name: "Site croissance", price: "45 000 DA", description: "Un site riche en fonctionnalités pour donner plus d’élan à votre entreprise.", features: ["Jusqu’à 8 pages sur mesure", "Espace actualités ou blog", "Présentation de projets et filtres", "Inscription à la newsletter", "Revue performance et SEO", "Trois séries de retouches"] },
    ],
  },
  ar: {
    eyebrow: "خدمات تطوير الويب", title: "موقع ويب يمنح عملك حضورًا راسخًا.", intro: "نصمم ونبني مواقع سريعة ومتجاوبة تحوّل قصتك إلى خطوة تالية واضحة لعملائك.", cta: "ابدأ مشروعك", promise: "نطاق واضح. بناء عصري. جاهز للإطلاق.", processTitle: "مصمم حول احتياجات عملك.", process: ["مكالمة اكتشاف مركزة", "تصميم لكل الشاشات", "بناء سريع وسهل الوصول", "دعم الإطلاق والتسليم"], packagesTitle: "اختر نقطة البداية المناسبة", packagesNote: "تشمل كل باقة تصميمًا متجاوبًا ونموذج تواصل وإعدادًا أساسيًا لتحسين الظهور في البحث.", contact: "اطلب هذه الباقة", included: "ما تتضمنه الباقة", featured: "الأكثر شمولًا", imageOneAlt: "أشخاص يتعاونون حول طاولة", imageTwoAlt: "متحدث يقدم عرضًا أمام جمهور", packages: [
      { name: "الموقع الأساسي", price: "30,000 دج", description: "حضور رقمي أنيق لمشروع جديد أو علامة شخصية.", features: ["صفحة تعريفية مخصصة", "تصميم متجاوب للجوال", "نموذج تواصل وخريطة", "إعداد أساسي لمحركات البحث", "جولة مراجعة واحدة"] },
      { name: "موقع الأعمال", price: "37,500 دج", description: "مساحة أكبر لعرض قصتك وبناء الثقة وشرح خدماتك.", features: ["حتى 5 صفحات مخصصة", "أقسام للخدمات ومن نحن", "قسم أعمال أو معرض", "إعداد التحليلات", "جولتا مراجعة"] },
      { name: "موقع النمو", price: "45,000 دج", description: "موقع غني بالميزات يمنح عملك المتنامي زخمًا أكبر.", features: ["حتى 8 صفحات مخصصة", "قسم مدونة أو أخبار", "عرض مشاريع مع فلاتر", "دمج الاشتراك في النشرة", "مراجعة الأداء ومحركات البحث", "ثلاث جولات مراجعة"] },
    ],
  },
} as const;

export default async function ServicesPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const text = copy[locale as keyof typeof copy] ?? copy.en;

  return <main className="min-h-screen bg-[#f5f6f8] text-[#252525]"><ContentHeader locale={locale} />
    <section className="bg-[#202020] text-white"><div className="mx-auto grid max-w-[1320px] gap-10 px-4 py-14 sm:px-8 sm:py-20 lg:grid-cols-[minmax(0,1fr)_minmax(380px,.8fr)] lg:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#f7ced0]">{text.eyebrow}</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-7xl">{text.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/75 sm:text-lg">{text.intro}</p><a href={`/${locale}/request`} className="mt-8 inline-flex bg-[#8c1515] px-5 py-3 text-sm font-semibold transition-colors hover:bg-[#b1040e]">{text.cta} <span aria-hidden="true" className="ms-3">→</span></a></div><div className="relative min-h-[280px] overflow-hidden sm:min-h-[360px]"><Image src="https://undergrad.stanford.edu/sites/g/files/sbiybj20396/files/styles/responsive_large/public/media/image/img_3269_1_0.jpg.webp?itok=mSELQMrZ" alt={text.imageOneAlt} fill priority className="object-cover" sizes="(min-width: 1024px) 40vw, 100vw" /><div className="absolute inset-x-0 bottom-0 bg-[#8c1515] px-5 py-4 text-sm font-semibold">{text.promise}</div></div></div></section>
    <section className="mx-auto grid max-w-[1320px] gap-10 px-4 py-14 sm:px-8 sm:py-20 lg:grid-cols-[.75fr_1.25fr]"><div className="relative min-h-72 overflow-hidden"><Image src="https://a-us.storyblok.com/f/1023936/1504x1003/c5719b4da3/20240917_nso_convocation_95a5553-2.jpg/m/2000x1667/filters:quality(60):focal(503x287:504x288)" alt={text.imageTwoAlt} fill className="object-cover" sizes="(min-width: 1024px) 35vw, 100vw" /></div><div className="self-center"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#8c1515]">Tumbli Studio</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.045em] sm:text-5xl">{text.processTitle}</h2><ol className="mt-8 grid gap-4 sm:grid-cols-2">{text.process.map((step, index) => <li key={step} className="border-t border-[#c9c3b9] pt-3 text-sm font-medium"><span className="me-2 text-[#8c1515]">0{index + 1}</span>{step}</li>)}</ol></div></section>
    <section className="bg-[#e9e7e2] px-4 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-[1320px]"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#8c1515]">Web packages</p><div className="mt-3 flex flex-col justify-between gap-4 border-b border-[#c9c3b9] pb-8 sm:flex-row sm:items-end"><h2 className="max-w-xl text-4xl font-semibold tracking-[-.05em] sm:text-6xl">{text.packagesTitle}</h2><p className="max-w-sm text-sm leading-6 text-zinc-600">{text.packagesNote}</p></div><div className="mt-8 grid gap-px bg-[#c9c3b9] lg:grid-cols-3">{text.packages.map((pkg, index) => <article key={pkg.name} className={`relative flex flex-col bg-[#f7f7f5] p-6 sm:p-8 ${index === 2 ? "bg-[#8c1515] text-white" : ""}`}>{index === 2 && <p className="absolute right-0 top-0 bg-[#202020] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.14em] text-white">{text.featured}</p>}<p className={`text-sm font-semibold ${index === 2 ? "text-[#f7ced0]" : "text-[#8c1515]"}`}>{pkg.name}</p><p className="mt-6 text-4xl font-semibold tracking-[-.05em]">{pkg.price}</p><p className={`mt-4 min-h-14 text-sm leading-6 ${index === 2 ? "text-white/80" : "text-zinc-600"}`}>{pkg.description}</p><div className={`mt-7 border-t pt-5 ${index === 2 ? "border-white/25" : "border-[#c9c3b9]"}`}><p className="text-[10px] font-semibold uppercase tracking-[.14em]">{text.included}</p><ul className="mt-4 space-y-3 text-sm">{pkg.features.map((feature) => <li key={feature} className="flex gap-3"><span aria-hidden="true" className={index === 2 ? "text-[#f7ced0]" : "text-[#8c1515]"}>✓</span><span>{feature}</span></li>)}</ul></div><a href={`/${locale}/request`} className={`mt-8 inline-flex justify-between border-t pt-4 text-sm font-semibold transition-colors ${index === 2 ? "border-white/25 hover:text-[#f7ced0]" : "border-[#c9c3b9] hover:text-[#8c1515]"}`}>{text.contact}<span aria-hidden="true">→</span></a></article>)}</div></div></section>
    <JournalFooter locale={locale} />
  </main>;
}
