import Image from "next/image";
import { ContentHeader } from "@/components/content-header";
import { JournalFooter } from "@/components/journal-footer";

const copy = {
  en: { eyebrow: "About Tumbli", title: "Good ideas, made useful.", body: "Tumbli brings together thoughtful stories, practical platforms, and conversations that make everyday life more interesting.", founderLabel: "Founder", founderTitle: "Meet the person building Tumbli.", founderBody: "Founder Brintiel is shaping thoughtful digital products, communities and ideas with a practical point of view.", founderLink: "Visit founder.brintiel.com" },
  fr: { eyebrow: "À propos de Tumbli", title: "De bonnes idées, utiles au quotidien.", body: "Tumbli réunit des histoires inspirantes, des plateformes utiles et des conversations qui rendent le quotidien plus intéressant.", founderLabel: "Fondateur", founderTitle: "Découvrez la personne qui construit Tumbli.", founderBody: "Founder Brintiel crée des produits numériques, des communautés et des idées réfléchies avec une approche concrète.", founderLink: "Visiter founder.brintiel.com" },
  ar: { eyebrow: "عن تمبلي", title: "أفكار جيدة، مفيدة في الحياة.", body: "يجمع تمبلي القصص المدروسة والمنصات العملية والمحادثات التي تجعل الحياة اليومية أكثر إثارة للاهتمام.", founderLabel: "المؤسس", founderTitle: "تعرّف إلى الشخص الذي يبني تمبلي.", founderBody: "يبني Founder Brintiel منتجات رقمية ومجتمعات وأفكارًا مدروسة بمنظور عملي.", founderLink: "زيارة founder.brintiel.com" },
} as const;

export default async function AboutPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; const text = copy[locale as keyof typeof copy] ?? copy.en; return <main className="min-h-screen bg-[#f5f6f8] text-[#252525]"><ContentHeader locale={locale} /><section className="mx-auto max-w-4xl px-4 py-20 sm:px-8 sm:py-28"><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#8c1515]">{text.eyebrow}</p><h1 className="mt-4 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-0.055em] sm:text-7xl">{text.title}</h1><p className="mt-8 max-w-2xl text-xl leading-9 text-zinc-600">{text.body}</p><aside className="mt-14 grid gap-6 border-y border-[#c9c3b9] py-7 sm:grid-cols-[120px_1fr] sm:items-center"><Image src="https://founder.brintiel.com/static/images/profile-pic.png" alt="Founder Brintiel" width={120} height={120} className="size-24 rounded-full object-cover sm:size-[120px]"/><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#8c1515]">{text.founderLabel}</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">{text.founderTitle}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-600">{text.founderBody}</p><a href="https://founder.brintiel.com" target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-[#8c1515] underline underline-offset-4">{text.founderLink} →</a></div></aside></section><JournalFooter locale={locale} /></main>; }
