"use client";

import { FormEvent, useState } from "react";

export function AccountAccess({ locale, nextPath }: { locale: string; nextPath: string }) {
  const [mode, setMode] = useState<"login" | "register">("login"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json() as { error?: string }; if (!response.ok) { setLoading(false); setMessage(data.error ?? "Something went wrong."); return; } window.location.assign(nextPath || `/${locale}/dashboard`); }
  return <div className="bg-white p-6 shadow-[0_12px_30px_rgba(30,25,20,0.08)] sm:p-9"><div className="flex border-b border-[#d4cec5]"><button onClick={() => setMode("login")} className={`px-4 py-3 text-sm font-semibold ${mode === "login" ? "border-b-2 border-[#8c1515] text-[#8c1515]" : "text-zinc-500"}`}>Sign in</button><button onClick={() => setMode("register")} className={`px-4 py-3 text-sm font-semibold ${mode === "register" ? "border-b-2 border-[#8c1515] text-[#8c1515]" : "text-zinc-500"}`}>Create account</button></div><form onSubmit={submit} className="mt-7 grid gap-5"><label className="grid gap-2 text-sm font-semibold">Email address<input required name="email" type="email" autoComplete="email" className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /></label><label className="grid gap-2 text-sm font-semibold">Password<input required name="password" type="password" minLength={8} autoComplete={mode === "login" ? "current-password" : "new-password"} className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /></label><button disabled={loading} className="bg-[#8c1515] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[#b1040e] disabled:opacity-60">{loading ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button>{message && <p aria-live="polite" className="text-sm font-medium text-[#8c1515]">{message}</p>}</form></div>;
}
