"use client";

import { FormEvent, useRef, useState } from "react";

export function ContactForm({ text }: { text: { name: string; email: string; message: string; send: string } }) {
  const editor = useRef<HTMLDivElement>(null); const [content, setContent] = useState(""); const [sending, setSending] = useState(false); const [sent, setSent] = useState(false);
  function format(command: "bold" | "italic" | "insertUnorderedList") { editor.current?.focus(); document.execCommand(command); setContent(editor.current?.innerHTML ?? ""); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!content.trim()) return; setSending(true); window.setTimeout(() => { setSending(false); setSent(true); }, 550); }
  if (sent) return <div className="bg-white p-8 text-center shadow-[0_12px_30px_rgba(30,25,20,0.06)]"><span className="mx-auto grid size-11 place-items-center rounded-full bg-[#e2efe5] text-lg font-bold text-[#39754b]">✓</span><h2 className="mt-4 text-2xl font-semibold">Message sent!</h2><p className="mt-2 text-sm text-zinc-600">Thank you. We’ll be in touch soon.</p></div>;
  return <form onSubmit={submit} className="relative grid gap-5 bg-white p-6 shadow-[0_12px_30px_rgba(30,25,20,0.06)] sm:p-9">{sending && <div role="status" className="absolute inset-0 z-10 grid place-items-center bg-white/90"><span className="flex items-center gap-3 bg-[#252525] px-5 py-4 text-sm font-semibold text-white"><i className="size-5 animate-spin rounded-full border-2 border-white/30 border-t-white"/>Sending message…</span></div>}<label className="grid gap-2 text-sm font-semibold">{text.name}<input required className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /></label><label className="grid gap-2 text-sm font-semibold">{text.email}<input type="email" required className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /></label><div className="grid gap-2 text-sm font-semibold"><span>{text.message}</span><div className="border border-[#c9c3b9] focus-within:border-[#8c1515]"><div className="flex gap-1 border-b border-[#e4dfd7] bg-[#faf9f7] p-2"><button type="button" onClick={() => format("bold")} className="grid size-8 place-items-center font-bold hover:bg-[#ece8e1]">B</button><button type="button" onClick={() => format("italic")} className="grid size-8 place-items-center italic hover:bg-[#ece8e1]">I</button><button type="button" onClick={() => format("insertUnorderedList")} className="grid size-8 place-items-center hover:bg-[#ece8e1]">•≡</button></div><div ref={editor} contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" onInput={(event) => setContent((event.target as HTMLDivElement).innerHTML)} className="min-h-36 px-3 py-3 font-normal leading-6 outline-none empty:before:text-zinc-400 empty:before:content-['Write_your_message…']" /></div></div><button disabled={sending || !content.trim()} className="justify-self-start bg-[#8c1515] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[#b1040e] disabled:opacity-60">{text.send}</button></form>;
}
