"use client";

import Image from "next/image";
import { Link, usePathname } from "@/i18n/navigation";

const labels = {
  en: { discover: "Discover", services: "Services", products: "Products", platform: "Platform", about: "About", contact: "Contact", posts: "Posts", questions: "Q&A", featured: "Reinforcement learning", search: "Search stories and questions", menu: "Menu", language: "Language", chooseLanguage: "Choose language", linkedin: "Tumbli on LinkedIn", culture: "Culture", ideas: "Ideas", community: "Community" },
  fr: { discover: "Découvrir", services: "Services", products: "Produits", platform: "Plateforme", about: "À propos", contact: "Contact", posts: "Articles", questions: "Q&R", featured: "Apprentissage par renforcement", search: "Rechercher des articles et questions", menu: "Menu", language: "Langue", chooseLanguage: "Choisir la langue", linkedin: "Tumbli sur LinkedIn", culture: "Culture", ideas: "Idées", community: "Communauté" },
  ar: { discover: "اكتشف", services: "الخدمات", products: "المنتجات", platform: "المنصة", about: "من نحن", contact: "تواصل معنا", posts: "المقالات", questions: "الأسئلة والأجوبة", featured: "التعلّم المعزّز", search: "ابحث في المقالات والأسئلة", menu: "القائمة", language: "اللغة", chooseLanguage: "اختر اللغة", linkedin: "تمبلي على لينكدإن", culture: "الثقافة", ideas: "أفكار", community: "المجتمع" },
} as const;

const languageOptions = [{ locale: "en", label: "English", short: "EN" }, { locale: "fr", label: "Français", short: "FR" }, { locale: "ar", label: "العربية", short: "AR" }] as const;

function GlobeIcon() {
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" className="size-[18px]"><circle cx="12" cy="12" r="8.5"/><path d="M3.8 12h16.4M12 3.5c2.15 2.35 3.1 5.15 3.1 8.5s-.95 6.15-3.1 8.5c-2.15-2.35-3.1-5.15-3.1-8.5S9.85 5.85 12 3.5Z"/></svg>;
}

export function ContentHeader({ locale }: { locale: string }) {
  const text = labels[locale as keyof typeof labels] ?? labels.en;
  const pathname = usePathname();
  const links = [[text.discover, "/discover"], [text.services, "/services"], [text.products, "/products"], [text.platform, "/platform"], [text.about, "/about"], [text.contact, "/contact"], [text.posts, "/posts"], [text.questions, "/questions"], [text.featured, "/posts/reinforcement-learning-explained-from-q-learning-to-deep-q-networks"]] as const;
  const selectedLanguage = languageOptions.find((item) => item.locale === locale) ?? languageOptions[0];
  const languageMenu = <div className="absolute right-0 top-[calc(100%+10px)] z-[70] hidden w-48 overflow-visible border border-zinc-200 bg-[#f7f7f5] p-1.5 text-[#252525] shadow-[0_16px_35px_rgba(0,0,0,0.2)] group-open:block"><span aria-hidden="true" className="absolute -top-1.5 right-4 size-3 rotate-45 border-l border-t border-zinc-200 bg-[#f7f7f5]"/><div className="relative overflow-hidden"><p className="px-2.5 pb-1.5 pt-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-zinc-500">{text.language}</p>{languageOptions.map((item) => <Link key={item.locale} href={pathname} locale={item.locale} aria-current={item.locale === locale ? "page" : undefined} className={`flex items-center justify-between px-2.5 py-2.5 text-sm transition-colors hover:bg-zinc-200 ${item.locale === locale ? "bg-zinc-200 font-semibold text-[#8c1515]" : "text-zinc-700"}`}><span>{item.label}</span><span className="text-[10px] font-semibold text-zinc-400">{item.short}</span></Link>)}</div></div>;

  return <header className="relative z-40 bg-[#8c1515] text-white">
    <div className="border-b border-black/20 bg-[#78080d]"><div className="mx-auto flex min-h-11 max-w-[1320px] items-center gap-3 px-4 sm:px-8"><span className="hidden text-[10px] font-semibold uppercase tracking-[0.12em] sm:inline">Tumbli Journal</span><div className="hidden items-center gap-1 sm:flex"><a href={`/${locale}/discover`} className="bg-white/10 px-2.5 py-1 text-[10px] transition-colors hover:bg-black/80">{text.culture}</a><a href={`/${locale}/services`} className="bg-white/10 px-2.5 py-1 text-[10px] transition-colors hover:bg-black/80">{text.services}</a><a href={`/${locale}/projects`} className="bg-white/10 px-2.5 py-1 text-[10px] transition-colors hover:bg-black/80">{text.ideas}</a><a href={`/${locale}/questions`} className="bg-white/10 px-2.5 py-1 text-[10px] transition-colors hover:bg-black/80">{text.community}</a></div><form action={`/${locale}/search`} role="search" className="ml-auto flex h-9 w-[min(100%,300px)] items-center gap-2 border border-white/20 bg-[#f4f4f2] px-3 text-xs text-[#252525] shadow-sm transition-colors focus-within:bg-white focus-within:ring-2 focus-within:ring-white/50 sm:w-[330px]"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.25" className="size-[18px] shrink-0"><circle cx="11" cy="11" r="5"/><path d="m15 15 4 4"/></svg><input name="q" placeholder={text.search} className="min-w-0 flex-1 bg-transparent outline-none placeholder:text-zinc-500" /></form><a href="https://www.linkedin.com/in/tumbli" target="_blank" rel="noreferrer" aria-label={text.linkedin} className="hidden size-9 place-items-center border border-white/25 text-white transition-colors hover:bg-white hover:text-[#78080d] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white lg:grid"><svg aria-hidden="true" viewBox="0 0 24 24" fill="currentColor" className="size-[17px]"><path d="M5.3 3.5A1.8 1.8 0 1 1 5.3 7a1.8 1.8 0 0 1 0-3.5ZM3.8 8.5h3v11h-3v-11Zm5 0h2.9V10c.4-.8 1.4-1.8 3.3-1.8 3.5 0 4.1 2.3 4.1 5.3v6h-3v-5.3c0-1.3 0-2.9-1.8-2.9s-2.1 1.4-2.1 2.8v5.4h-3v-11Z"/></svg></a></div></div>
    <div className="mx-auto flex min-h-[68px] max-w-[1320px] items-center gap-4 px-4 sm:min-h-20 sm:px-8"><a href={`/${locale}`} aria-label="Tumbli home"><Image src="/tumbli-logo.png" alt="Tumbli" width={146} height={39} priority className="h-auto w-[118px] brightness-0 invert sm:w-[136px]" /></a><nav aria-label="Content navigation" className="ml-auto hidden items-center gap-4 text-xs font-medium xl:flex">{links.slice(0, 8).map(([label, path]) => <a key={path} href={`/${locale}${path}`} className="transition-colors hover:text-[#f7ced0]">{label}</a>)}</nav>
      <details className="group relative hidden xl:block"><summary aria-label={text.chooseLanguage} className="flex h-10 cursor-pointer list-none items-center gap-1.5 border border-white/25 bg-white/10 px-3 text-xs font-semibold transition-colors hover:bg-white/20 [&::-webkit-details-marker]:hidden"><GlobeIcon /><span>{selectedLanguage.short}</span><svg aria-hidden="true" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.8" className="size-3 transition-transform group-open:rotate-180"><path d="m3 6 5 5 5-5"/></svg></summary>{languageMenu}</details>
      <div className="ml-auto flex items-center xl:hidden"><a href="https://www.linkedin.com/in/tumbli" target="_blank" rel="noreferrer" aria-label={text.linkedin} className="grid size-10 place-items-center text-white transition-colors hover:bg-white/10 hover:text-[#f7ced0] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"><svg aria-hidden="true" viewBox="0 0 24 24" fill="currentColor" className="size-[17px]"><path d="M5.3 3.5A1.8 1.8 0 1 1 5.3 7a1.8 1.8 0 0 1 0-3.5ZM3.8 8.5h3v11h-3v-11Zm5 0h2.9V10c.4-.8 1.4-1.8 3.3-1.8 3.5 0 4.1 2.3 4.1 5.3v6h-3v-5.3c0-1.3 0-2.9-1.8-2.9s-2.1 1.4-2.1 2.8v5.4h-3v-11Z"/></svg></a><details className="group relative"><summary aria-label={text.chooseLanguage} className="grid size-11 cursor-pointer list-none place-items-center transition-colors hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white [&::-webkit-details-marker]:hidden"><GlobeIcon /></summary>{languageMenu}</details><details className="group relative"><summary aria-label={text.menu} className="relative z-[60] grid size-12 cursor-pointer list-none place-items-center transition-colors hover:bg-white/10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white [&::-webkit-details-marker]:hidden"><span className="grid gap-1.5"><i className="block h-0.5 w-6 bg-white transition-transform group-open:translate-y-2 group-open:rotate-45"/><i className="block h-0.5 w-6 bg-white transition-opacity group-open:opacity-0"/><i className="block h-0.5 w-6 bg-white transition-transform group-open:-translate-y-2 group-open:-rotate-45"/></span></summary><div className="fixed inset-0 z-50 overflow-y-auto bg-[#202020] pt-8 text-white"><div className="min-h-full border-r border-white/50 px-7 pb-12 pt-24 shadow-[12px_0_20px_rgba(0,0,0,0.32)]"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#f7ced0]">Tumbli Journal</p><nav aria-label="Mobile navigation" className="mt-12 grid gap-1">{links.map(([label, path]) => <a key={path} href={`/${locale}${path}`} className="flex items-center justify-between py-2 text-3xl font-semibold leading-tight tracking-[-0.05em] transition-colors hover:text-[#f7ced0]"><span>{label}</span><span aria-hidden="true" className="text-xl font-normal text-white/40">›</span></a>)}</nav></div></div></details></div>
    </div>
  </header>;
}
