import Link from "next/link";

const copy = {
  en: { explore: "Explore", topics: "Topics", discover: "Discover", posts: "Our posts", questions: "Questions & answers", search: "Search", culture: "Culture", wellbeing: "Wellbeing", ideas: "Ideas", travel: "Travel", summary: "Stories, questions, and good ideas for a more interesting everyday.", home: "Tumbli home", contact: "Contact", copyright: "© 2026 Tumbli. Made for your next good idea." },
  fr: { explore: "Explorer", topics: "Thèmes", discover: "Découvrir", posts: "Nos articles", questions: "Questions et réponses", search: "Rechercher", culture: "Culture", wellbeing: "Bien-être", ideas: "Idées", travel: "Voyage", summary: "Des histoires, des questions et de belles idées pour enrichir le quotidien.", home: "Accueil Tumbli", contact: "Contact", copyright: "© 2026 Tumbli. Créé pour votre prochaine bonne idée." },
  ar: { explore: "استكشف", topics: "المواضيع", discover: "اكتشف", posts: "مقالاتنا", questions: "الأسئلة والأجوبة", search: "بحث", culture: "الثقافة", wellbeing: "العافية", ideas: "أفكار", travel: "السفر", summary: "قصص وأسئلة وأفكار جيدة تجعل الحياة اليومية أكثر ثراءً.", home: "الرئيسية", contact: "تواصل معنا", copyright: "© 2026 تَمبلي. صُنع لفكرتك الجيدة القادمة." },
} as const;

export function JournalFooter({ locale }: { locale: string }) {
  const text = copy[locale as keyof typeof copy] ?? copy.en;
  const groups = [{ title: text.explore, links: [[text.discover, "/discover"], [text.posts, "/posts"], [text.questions, "/questions"], [text.search, "/search"]] }, { title: text.topics, links: [[text.culture, "/search?q=culture"], [text.wellbeing, "/search?q=wellbeing"], [text.ideas, "/search?q=ideas"], [text.travel, "/search?q=travel"]] }];
  return <footer className="relative mt-16 overflow-hidden bg-[#8c1515] pt-12 text-white sm:mt-24 sm:pt-16"><div aria-hidden="true" className="pointer-events-none absolute inset-x-0 bottom-0 flex h-56 items-end gap-4 opacity-20"><span className="h-44 flex-1 rounded-t-full bg-[#3e0608]" /><span className="h-56 flex-1 rounded-t-full bg-[#3e0608]" /><span className="h-44 flex-1 rounded-t-full bg-[#3e0608]" /></div><div className="relative mx-auto max-w-[1320px] px-4 sm:px-8"><div className="grid gap-10 border-b border-white/20 pb-12 sm:grid-cols-2 lg:grid-cols-[repeat(4,minmax(0,1fr))_1.5fr]"><div className="grid grid-cols-2 gap-8 sm:col-span-2 lg:contents">{groups.map((group) => <div key={group.title}><h2 className="text-sm font-semibold">{group.title}</h2><ul className="mt-4 space-y-2.5 text-xs text-white/85">{group.links.map(([label, path]) => <li key={label}><Link href={`/${locale}${path}`} className="transition-colors hover:text-[#f7ced0]">{label}</Link></li>)}</ul></div>)}</div><div className="lg:text-right"><p className="font-serif text-3xl font-semibold tracking-[-0.04em]">Tumbli Journal</p><p className="mt-3 max-w-xs text-sm leading-6 text-white/75 lg:ml-auto">{text.summary}</p></div></div><div className="relative flex flex-col gap-4 py-6 text-xs text-white/85 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-x-5 gap-y-2"><a href={`/${locale}`} className="font-semibold hover:text-[#f7ced0]">{text.home}</a><a href={`/${locale}/search`} className="font-semibold hover:text-[#f7ced0]">{text.search} Tumbli</a><a href={`/${locale}/contact`} className="font-semibold hover:text-[#f7ced0]">{text.contact}</a></div><p>{text.copyright}</p></div></div></footer>;
}
