"use client";

import { FormEvent, useState } from "react";
import { RichTextField } from "@/components/rich-text-field";

const packages = ["Starter site — 30,000 DA", "Business site — 37,500 DA", "Growth site — 45,000 DA"];
export function ServiceRequestForm({ locale }: { locale: string }) {
  const [step, setStep] = useState(1); const [sending, setSending] = useState(false); const [message, setMessage] = useState(""); const [trackingCode, setTrackingCode] = useState("");
  function next(_form?: HTMLFormElement) { setStep((value) => Math.min(3, value + 1)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setSending(true); setMessage(""); const response = await fetch("/api/service-requests", { method: "POST", body: new FormData(form) }); const data = await response.json() as { error?: string; trackingCode?: string }; setSending(false); if (!response.ok) { setMessage(data.error ?? "Something went wrong. Please try again."); return; } setTrackingCode(data.trackingCode ?? ""); setStep(4); }
  if (step === 4) return <div className="bg-white p-7 shadow-[0_12px_30px_rgba(30,25,20,0.08)] sm:p-9"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-[#8c1515]">Request submitted</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Your project is now being reviewed.</h2><p className="mt-4 text-sm leading-6 text-zinc-600">Your account was created automatically. Save this project tracking code; you can use it to follow this request without signing in.</p><p className="mt-6 border-l-4 border-[#8c1515] bg-[#f0ece7] px-4 py-3 font-mono text-lg font-bold tracking-[.08em] text-[#8c1515]">{trackingCode}</p><div className="mt-7 flex flex-wrap gap-3"><a href={`/${locale}/dashboard`} className="bg-[#8c1515] px-5 py-3 text-sm font-semibold text-white">Open my dashboard</a><a href={`/${locale}/track`} className="border border-[#8c1515] px-5 py-3 text-sm font-semibold text-[#8c1515]">Track with code</a></div></div>;
  return <form noValidate onSubmit={submit} className="relative bg-white p-6 shadow-[0_12px_30px_rgba(30,25,20,0.08)] sm:p-9">{sending && <div role="status" aria-live="polite" className="absolute inset-0 z-10 grid place-items-center bg-white/90"><div className="flex items-center gap-3 bg-[#252525] px-5 py-4 text-sm font-semibold text-white"><span className="size-5 animate-spin rounded-full border-2 border-white/30 border-t-white" />Sending your project request…</div></div>}<div className="grid grid-cols-3 border-b border-[#d9d4cb] pb-5 text-[10px] font-semibold uppercase tracking-[.12em] text-zinc-400">{["01 Account", "02 Project", "03 Media"].map((label, index) => <div key={label} className={step === index + 1 ? "text-[#8c1515]" : step > index + 1 ? "text-[#39754b]" : ""}>{label}</div>)}</div>
    <div hidden={step !== 1} className="mt-7 grid gap-5"><div><p className="text-xl font-semibold">Create your project account</p><p className="mt-2 text-sm leading-6 text-zinc-600">We will create your account automatically when you submit this request.</p></div><label className="grid gap-2 text-sm font-semibold">Email address<input required name="email" type="email" autoComplete="email" className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /></label><label className="grid gap-2 text-sm font-semibold">Choose a password<input required name="password" type="password" minLength={8} autoComplete="new-password" className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /><span className="text-xs font-normal text-zinc-500">At least 8 characters. Existing customers can use their current password.</span></label><button type="button" onClick={(event) => next(event.currentTarget.form!)} className="justify-self-start bg-[#8c1515] px-5 py-3 text-sm font-semibold text-white">Continue to project details</button></div>
    <div hidden={step !== 2} className="mt-7 grid gap-5"><div><p className="text-xl font-semibold">Tell us about the website</p><p className="mt-2 text-sm leading-6 text-zinc-600">The more context you share, the better we can prepare your proposal.</p></div><label className="grid gap-2 text-sm font-semibold">Business or project name<input required name="businessName" maxLength={120} className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /></label><label className="grid gap-2 text-sm font-semibold">Current website <span className="font-normal text-zinc-500">(optional)</span><input name="website" type="url" maxLength={300} placeholder="https://" className="border border-[#c9c3b9] px-3 py-3 font-normal outline-none focus:border-[#8c1515]" /></label><label className="grid gap-2 text-sm font-semibold">Preferred package<select required name="package" defaultValue="" className="border border-[#c9c3b9] bg-white px-3 py-3 font-normal outline-none focus:border-[#8c1515]"><option value="" disabled>Choose a package</option>{packages.map((item) => <option key={item}>{item}</option>)}</select></label><RichTextField name="richDescription" label="Website goals and desired features" placeholder="Tell us about your audience, pages, content, style and features you need."/><div className="flex gap-3"><button type="button" onClick={() => setStep(1)} className="border border-[#c9c3b9] px-5 py-3 text-sm font-semibold">Back</button><button type="button" onClick={(event) => next(event.currentTarget.form!)} className="bg-[#8c1515] px-5 py-3 text-sm font-semibold text-white">Continue to media</button></div></div>
    <div hidden={step !== 3} className="mt-7 grid gap-5"><div><p className="text-xl font-semibold">Add helpful references</p><p className="mt-2 text-sm leading-6 text-zinc-600">Upload up to four images, screenshots, or PDFs. Each file can be up to 10 MB.</p></div><label className="grid gap-2 text-sm font-semibold">Project media <span className="font-normal text-zinc-500">(optional)</span><input name="media" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" className="border border-dashed border-[#bcb4aa] bg-[#faf9f7] px-3 py-5 text-sm font-normal file:me-4 file:border-0 file:bg-[#8c1515] file:px-3 file:py-2 file:text-xs file:font-semibold file:text-white" /></label><div className="flex gap-3"><button type="button" onClick={() => setStep(2)} className="border border-[#c9c3b9] px-5 py-3 text-sm font-semibold">Back</button><button disabled={sending} className="bg-[#8c1515] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{sending ? "Sending request…" : "Send project request"}</button></div></div>{message && <p aria-live="polite" className="mt-5 text-sm font-medium text-[#8c1515]">{message}</p>}</form>;
}
