import { ContentHeader } from "@/components/content-header";
import { JournalFooter } from "@/components/journal-footer";
import { getProjects, plainText } from "@/lib/parse";

export const revalidate = 300;

export default async function ProjectsPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ q?: string; company?: string }> }) {
  const [{ locale }, { q = "", company = "" }] = await Promise.all([params, searchParams]);
  const projects = await getProjects(locale); const companies = [...new Set(projects.map((project) => project.company))].sort(); const term = q.trim().toLowerCase();
  const results = projects.filter((project) => (!company || project.company === company) && (!term || `${project.title} ${project.company} ${plainText(project.description)}`.toLowerCase().includes(term)));
  return <main className="min-h-screen bg-[#f5f6f8] text-[#252525]"><ContentHeader locale={locale} /><section className="mx-auto mt-8 max-w-[1320px] bg-[#252525] px-5 py-10 text-white sm:mt-12 sm:px-10 sm:py-14"><p className="text-3xl font-medium tracking-[-0.045em] sm:text-5xl">Find your project</p><p className="mt-1 text-3xl tracking-[-0.045em] text-[#ddd6cc] sm:text-5xl">Explore our platform offerings</p><form action={`/${locale}/projects`} className="mt-10 grid border border-white/40 sm:grid-cols-[minmax(0,1fr)_220px_auto]"><label className="flex items-center gap-3 border-b border-white/30 px-4 py-3 sm:border-b-0 sm:border-r"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="size-4 shrink-0"><circle cx="11" cy="11" r="5" /><path d="m15 15 4 4" /></svg><input name="q" defaultValue={q} placeholder="Search by keyword, e.g. “education”" className="w-full bg-transparent text-sm outline-none placeholder:text-white/70" /></label><select name="company" defaultValue={company} className="border-b border-white/30 bg-[#252525] px-4 py-3 text-sm outline-none sm:border-b-0 sm:border-r"><option value="">Any platform</option>{companies.map((item) => <option key={item} value={item}>{item}</option>)}</select><button className="bg-[#b1040e] px-6 py-3 text-sm font-semibold transition-colors hover:bg-[#d12a31]">Browse projects</button></form><p className="mt-4 text-xs text-white/75">Browse the platforms, products, and projects being built in our community.</p></section><section className="mx-auto max-w-[1100px] px-5 py-12 sm:px-8 sm:py-16"><div className="flex items-baseline justify-between border-b border-[#c9c3b9] pb-4"><h1 className="text-3xl font-semibold tracking-[-0.04em]">Projects</h1><span className="text-sm text-zinc-500">{results.length} available</span></div><div className="divide-y divide-[#c9c3b9] border-b border-[#c9c3b9]">{results.map((project, index) => <article key={project.id} className="grid gap-4 py-7 sm:grid-cols-[100px_minmax(0,1fr)_auto] sm:items-start sm:gap-7"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#8c1515]">{String(index + 1).padStart(2, "0")}<br/><span className="mt-2 block text-zinc-500">{project.company}</span></p><div><h2 className="text-2xl font-semibold leading-tight tracking-[-0.035em]">{project.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-600">{plainText(project.description)}</p></div>{project.website && <a href={project.website} target="_blank" rel="noreferrer" className="self-end text-sm font-semibold text-[#8c1515] underline underline-offset-4 sm:self-center">Visit platform →</a>}</article>)}</div>{results.length === 0 && <p className="mt-8 text-sm text-zinc-600">No projects match this search. Try a different keyword or platform.</p>}</section><JournalFooter locale={locale} /></main>;
}
